$(".qiwi").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-10").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".FKWallet_RUB").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-1").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".FKWallet_USD").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-2").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})

$(".ЮMoney").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-3").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".VISA_RUB").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-4").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".VISA_MasterCard").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-5").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".VISA_MasterCardUAH").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-6").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".MasterCard_RUB").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-7").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".mir").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-8").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".online_bank ").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-9").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".cpb").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-11").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".SteamPay").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-12").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".PerfectMoneyUSD").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-13").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Bitcoin").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-14").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Litecoin").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-15").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Ethereum").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-16").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".USDTERC20").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-17").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".USDTTRC20").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-18").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".BitcoinCash").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-19").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".BNB").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-20").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".DASH").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-21").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Dogecoin").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-22").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".ZCash").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-23").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Monero").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-24").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Waves").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-25").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Ripple").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-26").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Shiba").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-27").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})
$(".Tron").click(function(event){
    $(".eiEWma").css("display", "none")
    $(".sc-kcbnda").css("display", "block")
    $(".sc-iomxrj").css("display", "none")
    $("#currency-28").css("display", "block")
    $("sc-qiwi").css("display", "flex")
    $("#submit-payment").css("background", "rgb(89, 69, 250)")
})